apiVersion: v1
kind: Service
metadata:
  name: agent-browser-controller
  labels:
    app.kubernetes.io/name: agent-browser-controller
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: agent-browser-controller
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
